### PR TITLE
Include "enable" in upstart for haas-proxy (first installation)

### PR DESCRIPTION
**Pull request by ooonea**
Added enable to haas-proxy service. Otherwise it will not start on reboot.

### CODE REVIEW

**Comment by BKPepe** [comment]
Hello @lucenera!

Thank you for your contribution. I think there isn't anything wrong to include enable there as well as start. This is common approach within OpenWrt.
Because this can cover cases when our patch with services_wanted [1] does not work as it should. It should be enabled automatically once Honeypot as Service is installed. 🤔But doing this manually does not harm.

Can you please update commit subject to be more related to commit description? After that, I can approve it.

[1] https://gitlab.nic.cz/turris/turris-build/-/blob/v5.1.4/patches/openwrt/hack/0001-base-files-do-not-automatically-activate-services-an.patch#L66

**Comment by ooonea** [comment]
I changed the commit subject. I hope this goes better 😉

**Review by BKPepe — APPROVED** [review]

**Comment by BKPepe** [comment]
This is going to be properly by this issue https://gitlab.nic.cz/turris/reforis/reforis-data-collection/-/issues/5 , but including enable should not harm and it is common approach in OpenWrt, so @ljelinek-cznic can you merge this? :)

**Comment by BKPepe** [comment]
It is now part of our repository. For reference commit: https://github.com/CZ-NIC/turris-user-docs/commit/0eabb0a9ce069479b80ae5121ade79b10fae9b0e

Thank you for your contribution.

**Pull request closed without merging**
